apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desafio-alice
  namespace: desafio-alice
  labels:
    app.kubernetes.io/name: desafio-alice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: desafio-alice
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
