apiVersion: v1
kind: Service
metadata:
  name: desafio-alice
  namespace: desafio-alice
  labels:
    app.kubernetes.io/name: desafio-alice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: desafio-alice
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
